### ISSUE TITLE
root用户权限问题

### ISSUE THREAD

**Issue by steven756284184** [XTLS/Xray-install#12]
使用 -u root 参数安装后，使用 xray.service 无法打开证书，日志显示 Permission denied. 经检查发现是 xray.service 中第 8 行``CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE``的问题，注释掉这一行就可以正常使用。我并不太懂 service
 配置文件的写法，供大佬参考！

**Comment by xiaoyaoyuxin** [comment]
这都能被你发现……

我也遇到同样的状况，点赞！

**Comment by rprx** [comment]
https://github.com/XTLS/Xray-install/pull/14

请试试 dev 分支的脚本是否解决了问题

**Comment by steven756284184** [comment]
已测试，dev 分支脚本可以正常使用。辛苦修改。

**Comment by rprx** [comment]
main 分支已更新，感谢反馈

**Comment by nonoricardo** [comment]
****问了一下chatgpt

这一项是什么#CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE****

回答：
这个配置项是 Linux 系统中 systemd 服务单元的一个参数 CapabilityBoundingSet，用于限制进程的能力（capabilities）。在这个配置中，CapabilityBoundingSet 参数用来指定进程的最终能力集，即允许进程拥有的特权和能力。

CAP_NET_ADMIN：这个能力允许进程执行网络相关的管理任务，比如配置网络接口、防火墙规则等。
CAP_NET_BIND_SERVICE：这个能力允许进程绑定到小于 1024 的端口，这些端口通常是一些特权端口，需要特殊权限才能绑定。
启用这两个能力意味着该进程具有网络管理和绑定特权端口的能力。在一些情况下，如果特权不当使用或者未经充分的安全考虑，可能会导致系统安全风险。因此，在配置时需要根据具体情况进行评估和权衡，并确保合理使用和保护系统安全。
如果您需要进一步了解或有其他问题，请随时告诉我！我会尽力协助您。
