### ISSUE TITLE
systemd unit file path should be /usr/local/lib/systemd/system

### ISSUE THREAD

**Issue by xiruizhao** [XTLS/Xray-install#13]
https://www.freedesktop.org/software/systemd/man/systemd.unit.html

Path | Description
-- | --
/etc/systemd/system | System units created by the administrator
/usr/local/lib/systemd/system | System units installed by the administrator
/usr/lib/systemd/system | System units installed by the distribution package manager

**Comment by rprx** [comment]
或许安装脚本属于 `created`，而包管理器才属于 `installed`？麻烦 @dctxmei

**Comment by dctxmei** [comment]
On Mon, Dec 28, 2020 at 11:42:23PM -0800, RPRX wrote:
> 或许安装脚本属于 `created`，而包管理器才属于 `installed`？麻烦 @dctxmei
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/XTLS/Xray-install/issues/13#issuecomment-751983049

這是一個灰色問題。

This is a gray question.

一方面，/etc/systemd/system/ 被認為是用於放置非軟體包管理安裝的單元檔案的常規管理位置。

On the one hand, /etc/systemd/system/ is considered to be the general management location for placing unit files for non-package management installations.

另一方面，如果打算嚴格的遵守 FHS，那麼這些檔案就應該放置到 /usr/local/lib/systemd/system/ 下。

On the other hand, if you plan to strictly comply with the FHS, then these files should be placed under /usr/local/lib/systemd/system/ .
-- 
Dct Mei

-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEXCinkBYJKwYBBAHaRw8BAQdA5H9IxywOaNmJIWhPWmOW373e5qV9B2XX4uaN
8Dj/os60G0RjdCBNZWkgPGRjdHhtZWlAZ21haWwuY29tPoiQBBMWCAA4FiEEezFL
5328og4C3bvAUL+LcS3K1+oFAlwop5ACGwMFCwkIBwIGFQoJCAsCBBYCAwECHgEC
F4AACgkQUL+LcS3K1+pb5AD9Em35W0ACv4sd1wsDLscHUP/9bsso4qz8Jakh49Tc
5MwBALgLJfruyp+waU/TgJNR9bfAntsN59NUvoElC0b/P94LuDgEXCinkBIKKwYB
BAGXVQEFAQEHQDGv8eGzsh+tFkh8Yfibp4Mtv94AwyN45x1AguzUVUcjAwEIB4h4
BBgWCAAgFiEEezFL5328og4C3bvAUL+LcS3K1+oFAlwop5ACGwwACgkQUL+LcS3K
1+pHggEA0QzrA6N+72SKchinmmaH1vBk8zcg8EGfxTTMgvttRQUBAL+SqHLwuhfV
OHgQi6COC+SQI5jrRAYhjrJoc+KHvHMI
=F48x
-----END PGP PUBLIC KEY BLOCK-----

**Comment by rprx** [comment]
最终决定还是 `/etc/systemd/system`：

1. `.service` 文件可能会被手动编辑，某种程度上符合定义
2. 这个路径看着顺眼、容易找到，目前不倾向于 breaking
3. 安装位置与 v2fly-core 相同，学习成本低，利于迁移
