### ISSUE TITLE
~/var/log/xray/access.log安装了但未使用~

### ISSUE THREAD

**Issue by xiruizhao** [XTLS/Xray-install#17]
~需要改动https://github.com/XTLS/Xray-core/blob/be9421fedf9017f1ea48c292a2ba7c9d8e3ed9dc/common/log/logger.go#L151~
~另外~,没有安装`logrotate(8)`配置`/etc/logrotated.d/xray`。`/var/log/xray/access.log`的perms也不合理，应改成owner=nobody/root,group=adm,mode=640。

**Comment by badO1a5A90** [comment]
我觉得logrotate不是必需的，没必要一并安装设定
另外，没明白你说的但未使用和需要改动是指什么要做到什么样的结果

**Comment by kirin10000** [comment]
log文件的安装行为和上游 https://github.com/v2fly/fhs-install-v2ray 是一样的。你可以试试在那边提问，感觉他们挺注重这些东西的

**Comment by rprx** [comment]
创建此文件是因为之前很多人会先以 root 权限测试软件，导致生成的日志文件属于 root，默认安装的 nobody 无法访问

**Comment by xiruizhao** [comment]
但是现在nobody nogroup 600导致管理用户都不能读log。至少要改成nobody adm 640。

**Comment by xiruizhao** [comment]
我指的是非root且在adm group的系统用户，例如AWS Ubuntu默认管理用户叫ubuntu，nginx log的权限就是root adm 640。

> Group adm is used for system monitoring tasks. Members of this group can read many log files in /var/log, and can use xconsole.
https://www.debian.org/doc/manuals/securing-debian-manual/ch12.en.html

**Comment by xiruizhao** [comment]
> 我觉得logrotate不是必需的，没必要一并安装设定
不加logrotate任留log堆满磁盘？
> 另外，没明白你说的但未使用和需要改动是指什么要做到什么样的结果
xray-core现在的logger输出到stdout而不是log file。log现在都堆在systemd journal里。

**Comment by badO1a5A90** [comment]
> > 我觉得logrotate不是必需的，没必要一并安装设定
> 
> 不加logrotate任留log堆满磁盘？
> 
> > 另外，没明白你说的但未使用和需要改动是指什么要做到什么样的结果
> 
> xray-core现在的logger输出到stdout而不是log file。log现在都堆在systemd journal里。

怎么处理log文件不是Xray的事情, 用户也可以有各种方式自行处理, 其他一键脚本也可以提供, 纯安装Xray的脚本不必关心这个.

**Comment by xiruizhao** [comment]
既然创建了log文件就应该加logrotate配置，nginx都安装了。一个Debian安装包是肯定要logrotate配置的，为啥这个安装脚本就不加呢？我有空研究一下弄个pr吧。
