### ISSUE TITLE
systemctl start 失败

### ISSUE THREAD

**Issue by DarrenLuo** [XTLS/Xray-install#2]
系统版本：ubuntu 20.04
安装脚本使用的用户：root

排查过程：
1. 执行 `systemctl status xray`：
```
xray.service - Xray Service
     Loaded: loaded (/etc/systemd/system/xray.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/xray.service.d
             └─10-donot_touch_single_conf.conf
     Active: failed (Result: exit-code) since Fri 2020-12-11 06:19:29 UTC; 1s ago
       Docs: https://github.com/xtls
    Process: 251643 ExecStart=/usr/local/bin/xray run -config /usr/local/etc/xray/config.json (code=exited, status=1/FAILURE)
   Main PID: 251643 (code=exited, status=1/FAILURE)

Dec 11 06:19:29 vultr.guest systemd[1]: xray.service: Main process exited, code=exited, status=1/FAILURE
Dec 11 06:19:29 vultr.guest systemd[1]: xray.service: Failed with result 'exit-code'.
Dec 11 06:19:29 vultr.guest systemd[1]: xray.service: Scheduled restart job, restart counter is at 5.
Dec 11 06:19:29 vultr.guest systemd[1]: Stopped Xray Service.
Dec 11 06:19:29 vultr.guest systemd[1]: xray.service: Start request repeated too quickly.
Dec 11 06:19:29 vultr.guest systemd[1]: xray.service: Failed with result 'exit-code'.
Dec 11 06:19:29 vultr.guest systemd[1]: Failed to start Xray Service.
```
2. 在上面没有找到有用的信息，使用 `journalctl --boot -u xray` 命令进行排查
3. 最后对日志目录和配置目录使用了 `chown -R nobody: nogroup` 命令，修改 `/etc/systemd/system/xray.service` 用的 User 为 root，执行 `systemctl daemon-reload` 后 start 就成功了

没有仔细的找原因，先做一个记录

**Comment by DarrenLuo** [comment]
好像是证书权限的问题，后面再排查

**Comment by xiaoyaoyuxin** [comment]
遇到了同样的问题。应该是证书权限的问题。
我配合宝塔面板使用的，用宝塔面板申请的证书，证书放在/www/server/panel/vhost/cert/域名 的目录下，启动失败。
后来手动移到了/usr/local/etc/xray/ssl下面，就成功启动了。

**Comment by crackerjohn** [comment]
遇到同样问题，调整证书位置之后启动失败信息变成这样
● xray.service - Xray Service
   Loaded: loaded (/etc/systemd/system/xray.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/xray.service.d
           └─10-donot_touch_single_conf.conf
   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-12-15 01:56:23 EST; 62ms ago
     Docs: https://github.com/xtls
  Process: 631 ExecStart=/usr/local/bin/xray run -config /usr/local/etc/xray/config.json (code=exited, status=1/FAILURE)
 Main PID: 631 (code=exited, status=1/FAILURE)

**Comment by DarrenLuo** [comment]
@crackerjohn 修改一下文件的 owner 就可以，主要是权限的问题，启动用户是 nobody

**Comment by rprx** [comment]
请使用最新的脚本 https://github.com/XTLS/Xray-install
