### ISSUE TITLE
Windows服务端怎么安装呢

### ISSUE THREAD

**Issue by qian9008** [XTLS/Xray-install#20]
主要是配置文件不会写

**Comment by SekiBetu** [comment]
![image](https://user-images.githubusercontent.com/38283893/108592748-65885480-73aa-11eb-9510-233e6ce5434f.png)

**Comment by 1265578519** [comment]
不清楚，没人做Windows的服务端

**Comment by rprx** [comment]
> Windows服务端怎么安装呢

目前没有 Windows 上的安装脚本，其实简单让它开机启动 Xray-core 即可。

> 主要是配置文件不会写

如果你指的是 Xray-core 的配置文件，一般来说和 Linux 服务端的完全一样。
