### ISSUE TITLE
跳板怎么设置？

### ISSUE THREAD

**Issue by SemiThin** [XTLS/Xray-install#57]
原因：移动网络无法直接访问VPS，所以想借助跳板，不得不说移动网络真垃

现有阿里服务器

怎么在家用电脑通过阿里服务器访问VPS呢

目前只会客户端和服务端的配置方式

**Comment by KoinuDayo** [comment]
家里outbound到阿里云的inbound，然后阿里云再路由这个inbound到vps的inbound
家out`
{
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "阿里云",
            "port": 63227,
            "users": [
              {
                "id": "",
                "alterId": 0,
                "security": "auto"
              }
            ]
          }
        ]
     }
`
阿里云in`
		{
	  "tag": "vmess" ,
      "port": 63227,
      "protocol": "vmess",
      "settings": {
        "udp": false,
        "clients": [
          {
            "id": "",
            "alterId": 0
        ]，
   }
`
阿里云out`{
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "vps",
            "port": 63227,
            "users": [
              {
                "id": "",
                "alterId": 0,
                "security": "auto"
              }
            ]
          }
        ]
     }
`

**Comment by SemiThin** [comment]
> 家里outbound到阿里云的inbound，然后阿里云再路由这个inbound到vps的inbound 家out`{ "tag": "proxy", "protocol": "vmess", "settings": { "vnext": [ { "address": "阿里云", "port": 63227, "users": [ { "id": "", "alterId": 0, "security": "auto" } ] } ] }` 阿里云in`{ "tag": "vmess" , "port": 63227, "protocol": "vmess", "settings": { "udp": false, "clients": [ { "id": "", "alterId": 0 ]， }` 阿里云out`{ "tag": "proxy", "protocol": "vmess", "settings": { "vnext": [ { "address": "vps", "port": 63227, "users": [ { "id": "", "alterId": 0, "security": "auto" } ] } ] } `

感谢你的思路，成功了
