### ISSUE TITLE
`--no-service` mode

### ISSUE THREAD

**Issue by APT-ZERO** [XTLS/Xray-install#71]
Hello
Please add --no-service mode to just download or upgrade xray-core to latest version without installing any service
Useful for some panels and custom scripts
Thank you

**Comment by Edwin-Kevin** [comment]
@APT-ZERO 那直接 wget 拉一下不就好了

**Comment by chise0713** [comment]
Why you want this feature? If you don't want service then just simply `systemctl disable --now xray`
