### ISSUE TITLE
脚本有个文本错误

### ISSUE THREAD

**Issue by cygauss** [XTLS/Xray-install#72]
help中    --logrotate 项有写  under 12:00:00 should be start with 0, e.g. 01:23:45. 这里12应该是10吧

**Comment by Fangliding** [comment]
哈哈哈哈 够细

**Comment by chise0713** [comment]
我的，写的时候没带脑子

**Comment by SodaWithoutSparkles** [comment]
不是，这节regex是match符合还是不符合的？我输入"12:34:56"也错的

是不是逻辑反转了

**Comment by chise0713** [comment]
~~好像是我写错了~~

**Comment by chise0713** [comment]
不对，没错

**Comment by SodaWithoutSparkles** [comment]
抽了那一片程序测试，没问题

```
if ! grep -qE '\b([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]\b' <<< "00:00:00"; then

  echo "wrong"

fi
```

**Comment by chise0713** [comment]
> 抽了那一片程序测试，没问题
> 
> ```
> if ! grep -qE '\b([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]\b' <<< "00:00:00"; then
> 
>   echo "wrong"
> 
> fi
> ```

https://github.com/XTLS/Xray-install/commit/34df513a033afa2c64e4fa2353185c56e84a1ae9#diff-b987da59f640929590fd09160a2098fa77a731a75ff5de3e88be9996e0b62e5dR303
~~我这里是忘记取反了~~

**Comment by SodaWithoutSparkles** [comment]
Resolved by #73

是不是可以关掉issue 了？
