### ISSUE TITLE
xray可能有后门

### ISSUE THREAD

**Issue by fuckrprx** [XTLS/Xray-install#76]
建议使用[sing-box](https://github.com/SagerNet/sing-box)

**Comment by chise0713** [comment]
I found that [backdoor](https://github.com/XTLS/Xray-core/blob/41d03d1856a5b16521610792601a20fb1195418e/proxy/shadowsocks_2022/outbound.go#L7-L13)

**Comment by RPRX** [comment]
你妈也有后门

**Comment by RPRX** [comment]
你妈也有后门你怎么不说？删了

**Comment by RPRX** [comment]
To 球球：人家的 username 就是 fuckrprx，这个账号发了三个攻击性 issue，所以我说的就是字面意思，有妈生没妈养的孤儿
